name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t my-html-app .

    - name: Stop and Remove Old Container
      run: |
        docker stop my-html-container || true
        docker rm my-html-container || true

    - name: Run New Container
      run: docker run -d -p 8080:80 --name my-html-container my-html-app

    - name: Wait for Container to Initialize
      run: sleep 15

    - name: Perform Integration Test
      run: |
        echo "Running integration test..."
        STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8080)
        if [ "$STATUS_CODE" -eq 200 ]; then
          echo "✅ Test Passed! Status Code: $STATUS_CODE"
        else
          echo "❌ Test Failed! Status Code: $STATUS_CODE"
          exit 1
        fi

    - name: Check Running Containers
      run: |
        docker ps -a
        docker logs my-html-container || true

